@baseUrl = localhost:3000/v1

### Create a post
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "My",
    "content": "This is my first post",
    "tags": ["first", "post"]
}

### Get a post 
GET {{baseUrl}}/posts/101

### List posts
GET {{baseUrl}}/posts

